# Generated by Django 5.2.7 on 2025-11-06 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date',), 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
