# Generated by Django 5.2.7 on 2025-11-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, null=True, to='school.lesson', verbose_name='уроки'),
        ),
    ]
