# Generated by Django 5.2.7 on 2025-11-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_lesson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, null=True, related_name='course', to='school.lesson', verbose_name='уроки'),
        ),
    ]
