# Generated by Django 5.2.7 on 2025-11-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_course_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='courses', to='school.lesson', verbose_name='уроки'),
        ),
    ]
